require 'rake'
require 'config'

task :default => 'clean'

desc "Remove files rubinius/*"
task :clean do
  system 'rm -rf #{INSTALL_DIR}/*'
  system 'cd ../rubinius && rake clean:all'
end

desc "Install rubinius for debian package"
task :install => :clean do
  system "cd ../rubinius && PREFIX=#{INSTALL_DIR} rake build"
  system "cd ../rubinius && PREFIX=#{INSTALL_DIR} rake install"
end

desc "Publish package"
task :publish do
  puts "=> uploading to #{USER}@#{SERVER}:#{UPLOAD_DIR} ..."
  system "scp ../#{DEB_FILE} #{USER}@#{SERVER}:#{UPLOAD_DIR}"
end

