Document: rubinius
Title: Debian rubinius Manual
Author: <insert document author here>
Abstract: This manual describes what rubinius is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rubinius/rubinius.sgml.gz

Format: postscript
Files: /usr/share/doc/rubinius/rubinius.ps.gz

Format: text
Files: /usr/share/doc/rubinius/rubinius.text.gz

Format: HTML
Index: /usr/share/doc/rubinius/html/index.html
Files: /usr/share/doc/rubinius/html/*.html


